name: Update gist
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Update gist
        uses: maxam2017/productive-box@master
        env:
          GH_TOKEN: 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
          GIST_ID: https://gist.github.com/fredkeemhaus/
          TIMEZONE: Asia/Seoul
